### ISSUE TITLE
Add convenient methods for checking the ETH/DAI/USDC amounts in the user's wallet

### ISSUE THREAD

**Issue by BrendanChou** [dydxprotocol/dydx-python#16]

**Comment by IvoCrnkovic** [comment]
My original comment:

Is there a way through solo (ideally with a python wrapper) to poll the balances of the wallet associated with a dydx account?  Ofc theres `client.get_balances` but afaik that only gives you the account balances, not the balances of the wallet associated with the account.

**Comment by IvoCrnkovic** [comment]
This one is actually blocking me:

```
get_my_wallet_balances()
"""
returns the balances in the wallet associated with my dydx account.
"""

get_wallet_balances(address):
"""
returns the balances in a wallet associated with some dydx account.
"""
```
